eureka_odometry:
  ros__parameters:
    odometry_pub_topic: "~/odometry"
    twist_pub_topic: "~/twist_stamped"
    joint_sub_topic: "/wheel_states"
    imu_sub_topic: "/imu/data"
    enable_odom_tf: false
    wheel_radius: 0.29
    wheel_base: 0.71
    wheel_track: 0.951
    measure_error: 0.06